"""app/utils/helpers.py — Date, formatting, and export utilities"""

from datetime import datetime, timedelta


def date_range(start: str, end: str) -> list[str]:
    """Return list of date strings between start and end inclusive."""
    s = datetime.strptime(start, "%Y-%m-%d")
    e = datetime.strptime(end,   "%Y-%m-%d")
    return [(s + timedelta(days=i)).strftime("%Y-%m-%d") for i in range((e-s).days + 1)]


def nights_between(check_in: str, check_out: str) -> int:
    """Number of nights between two date strings."""
    try:
        ci = datetime.strptime(check_in,  "%Y-%m-%d")
        co = datetime.strptime(check_out, "%Y-%m-%d")
        return max(1, (co - ci).days)
    except Exception:
        return 1


def format_currency(amount: float, currency: str = "USD") -> str:
    symbols = {"USD":"$","EUR":"€","GBP":"£","JPY":"¥","INR":"₹","AUD":"A$","CAD":"C$"}
    sym = symbols.get(currency, currency + " ")
    return f"{sym}{amount:,.0f}"


def export_itinerary_text(itin: dict) -> str:
    """Generate a plain-text export of an itinerary."""
    lines = []
    sep   = "=" * 60

    lines.append(sep)
    lines.append(f"  {itin.get('title','Trip Itinerary').upper()}")
    lines.append(sep)
    lines.append(f"  Destination : {itin.get('dest_name','')} , {itin.get('country','')}")
    lines.append(f"  Hotel       : {itin.get('hotel_name','TBD')}")
    lines.append(f"  Dates       : {itin.get('start_date','')} → {itin.get('end_date','')}")
    lines.append(f"  Duration    : {itin.get('num_days',0)} days")
    lines.append(f"  Travelers   : {itin.get('num_travelers',1)}")
    lines.append(f"  Style       : {itin.get('travel_style','balanced').title()}")
    lines.append("")

    for day in itin.get("days", []):
        lines.append("-" * 60)
        lines.append(f"  DAY {day['day_number']}  —  {day.get('date_label', day['date'])}")
        lines.append(f"  Theme: {day.get('theme','')}")
        lines.append("")

        for slot_name, events in [
            ("🌅 MORNING",   day.get("morning",[])),
            ("☀️  AFTERNOON", day.get("afternoon",[])),
            ("🌙 EVENING",   day.get("evening",[])),
        ]:
            if events:
                lines.append(f"  {slot_name}")
                for e in events:
                    lines.append(f"    {e.get('time','')}  {e.get('emoji','')}  {e['name']}  ({e.get('duration','')})")
                    if e.get("tip"):
                        lines.append(f"           ↳ {e['tip']}")
                lines.append("")

        meals = day.get("meals", {})
        if meals:
            lines.append("  🍽️  MEALS")
            for meal_name in ["breakfast","lunch","dinner"]:
                m = meals.get(meal_name)
                if m:
                    lines.append(f"    {meal_name.title():12s} {m.get('emoji','')}  {m['name']}  ({m.get('cuisine','')}  {m.get('price','')})")
            lines.append("")

        if day.get("notes"):
            lines.append(f"  💡 {day['notes']}")
            lines.append("")

    lines.append(sep)
    lines.append("  Generated by Trip Planner  🌍")
    lines.append(sep)

    return "\n".join(lines)